const codeExamples = {
  javascript:
    "class Node {\n  constructor(data) {\n    this.data = data;\n    this.next = null;\n  }\n}\n\nfunction search(head, target) {\n  let current = head;\n  let index = 0;\n  while (current) {\n    if (current.data === target) return index;\n    current = current.next;\n    index++;\n  }\n  return -1;\n}\n\nlet head = new Node(10);\nhead.next = new Node(20);\nhead.next.next = new Node(30);\nconsole.log(search(head, 20));",
  python:
    "class Node:\n    def __init__(self, data):\n        self.data = data\n        self.next = None\n\ndef search(head, target):\n    current = head\n    index = 0\n    while current:\n        if current.data == target:\n            return index\n        current = current.next\n        index += 1\n    return -1\n\nhead = Node(10)\nhead.next = Node(20)\nhead.next.next = Node(30)\nprint(search(head, 20))",
  java: "class Node {\n    int data;\n    Node next;\n    Node(int data) {\n        this.data = data;\n        this.next = null;\n    }\n}\n\npublic class Main {\n    public static int search(Node head, int target) {\n        Node current = head;\n        int index = 0;\n        while (current != null) {\n            if (current.data == target) return index;\n            current = current.next;\n            index++;\n        }\n        return -1;\n    }\n\n    public static void main(String[] args) {\n        Node head = new Node(10);\n        head.next = new Node(20);\n        head.next.next = new Node(30);\n        System.out.println(search(head, 20));\n    }\n}",
  c: '#include <stdio.h>\n#include <stdlib.h>\n\nstruct Node {\n    int data;\n    struct Node* next;\n};\n\nint search(struct Node* head, int target) {\n    struct Node* current = head;\n    int index = 0;\n    while (current != NULL) {\n        if (current->data == target) return index;\n        current = current->next;\n        index++;\n    }\n    return -1;\n}\n\nint main() {\n    struct Node* head = (struct Node*)malloc(sizeof(struct Node));\n    struct Node* second = (struct Node*)malloc(sizeof(struct Node));\n    struct Node* third = (struct Node*)malloc(sizeof(struct Node));\n\n    head->data = 10;\n    head->next = second;\n    second->data = 20;\n    second->next = third;\n    third->data = 30;\n    third->next = NULL;\n\n    printf("%d\\n", search(head, 20));\n\n    return 0;\n}',
  cpp: "#include <iostream>\nusing namespace std;\n\nclass Node {\npublic:\n    int data;\n    Node* next;\n    Node(int data) : data(data), next(nullptr) {}\n};\n\nint search(Node* head, int target) {\n    Node* current = head;\n    int index = 0;\n    while (current != nullptr) {\n        if (current->data == target) return index;\n        current = current->next;\n        index++;\n    }\n    return -1;\n}\n\nint main() {\n    Node* head = new Node(10);\n    head->next = new Node(20);\n    head->next->next = new Node(30);\n\n    cout << search(head, 20) << endl;\n\n    Node* temp;\n    while (head != nullptr) {\n        temp = head;\n        head = head->next;\n        delete temp;\n    }\n\n    return 0;\n}",
};

export default codeExamples;
