"use client";
import ComplexityGraph from "@/app/components/ui/graph";
import { useTheme } from "@/app/contexts/ThemeContext";
import DailyDSAEmbed from "@/app/components/ui/DailyDSAEmbed";
import NewsletterEmbed from "@/app/components/ui/NewsletterEmbed";
import InContentAd from "@/app/components/ads/InContentAd";
import { motion } from "framer-motion";

const MiniTree = ({ nodes, edges, x0 }) => {
  const byId = Object.fromEntries(nodes.map((n) => [n.id, n]));
  return (
    <>
      {edges.map(([from, to], i) => (
        <motion.path
          key={`${x0}-${from}-${to}`}
          d={`M ${byId[from].x} ${byId[from].y} L ${byId[to].x} ${byId[to].y}`}
          fill="none"
          stroke="#818cf8"
          strokeWidth="2"
          initial={{ pathLength: 0, opacity: 0 }}
          animate={{ pathLength: 1, opacity: 1 }}
          transition={{ duration: 0.4, delay: 0.15 + i * 0.1, ease: "easeInOut" }}
        />
      ))}
      {nodes.map((n, i) => (
        <motion.g
          key={`${x0}-${n.id}`}
          initial={{ scale: 0, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ duration: 0.4, delay: 0.15 + i * 0.12, ease: "backOut" }}
          style={{ transformOrigin: `${n.x}px ${n.y}px` }}
        >
          {n.flipped && (
            <circle cx={n.x} cy={n.y} r="17" fill="none" stroke="#8b5cf6" strokeWidth="2" strokeDasharray="3 3" opacity="0.85" />
          )}
          <circle cx={n.x} cy={n.y} r="13" fill="#3b82f6" stroke="#1d4ed8" strokeWidth="2" />
          <text x={n.x} y={n.y + 4} textAnchor="middle" fill="#fff" fontSize="10" fontWeight="700">
            {n.id}
          </text>
        </motion.g>
      ))}
    </>
  );
};

const WalkthroughDiagram = () => {
  const nodesA = [
    { id: "1", x: 45, y: 25 },
    { id: "2", x: 25, y: 70 },
    { id: "3", x: 65, y: 70, flipped: true },
    { id: "4", x: 15, y: 115 },
    { id: "5", x: 35, y: 115 },
  ];
  const edgesA = [
    ["1", "2"],
    ["1", "3"],
    ["2", "4"],
    ["2", "5"],
  ];

  const nodesB = [
    { id: "1b", x: 175, y: 25 },
    { id: "3b", x: 155, y: 70, flipped: true },
    { id: "2b", x: 195, y: 70 },
    { id: "5b", x: 185, y: 115 },
    { id: "4b", x: 205, y: 115 },
  ];
  const edgesB = [
    ["1b", "3b"],
    ["1b", "2b"],
    ["2b", "5b"],
    ["2b", "4b"],
  ];

  return (
    <svg viewBox="0 0 220 130" className="w-full max-w-md mx-auto">
      <MiniTree nodes={nodesA} edges={edgesA} x0="a" />
      <MiniTree nodes={nodesB} edges={edgesB} x0="b" />
      <text x="110" y="70" textAnchor="middle" fontSize="12" className="fill-gray-400 dark:fill-gray-500">
        ≅
      </text>
    </svg>
  );
};

const Content = () => {
  const { theme } = useTheme();

  const paragraphs = [
    `Two binary trees are isomorphic if one can be transformed into the other by swapping the left and right children at any number of nodes: the values and the overall branching structure must match, but the left/right arrangement at each node is allowed to flip. It's a looser notion of "the same tree" than exact structural equality: two trees that look like mirror images of each other in places can still be isomorphic.`,
    `The check is a recursive comparison of two nodes at a time, starting from both roots. If both are empty, they match. If exactly one is empty, or their values differ, the trees aren't isomorphic. Otherwise, the node's children are compared two ways: "straight" (left-with-left, right-with-right) and "flipped" (left-with-right, right-with-left). If either pairing matches all the way down, the current pair of nodes is isomorphic.`,
    `This differs from an exact structural-equality check only in that extra flipped attempt: without it, this is the same algorithm used to test whether two trees are identical. The flip is what makes isomorphism forgiving of left/right orientation while still being strict about values and shape.`,
    `Isomorphism checks are common wherever "same shape regardless of arbitrary left/right layout choices" matters: comparing parse trees or expression trees generated by different tools, verifying that a serialized tree round-trips correctly regardless of child ordering, and canonicalizing tree-shaped data before hashing or deduplication.`,
  ];

  const algorithm = [
    { points: "If both nodes are null, they match" },
    { points: "If exactly one is null, or their values differ, the trees are not isomorphic: stop" },
    {
      points: "Otherwise, compare children two ways:",
      subpoints: [
        "Straight: left-with-left and right-with-right",
        "Flipped: left-with-right and right-with-left",
      ],
    },
    { points: "If either pairing matches recursively, the current nodes are isomorphic" },
  ];

  const complexity = [
    { points: "Time Complexity: O(n) in the best case, up to O(4^n) in the worst case for the naive version, though in practice close to O(n) for most trees since a mismatch usually short-circuits early." },
    { points: "Space Complexity: O(h), where recursion stack depth equals the smaller tree's height." },
  ];

  return (
    <main className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-12 md:gap-4">
      <div className="md:col-span-3">
        <NewsletterEmbed mobile={false} theme={theme} />
        <DailyDSAEmbed mobile={false} theme={theme} />
      </div>
      <article className="md:col-span-9 max-w-4xl bg-white dark:bg-neutral-950 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden mb-8">
        {/* What is Isomorphism */}
        <section className="p-6 border-b border-gray-100 dark:border-gray-700">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-4 flex items-center">
            <span className="w-1 h-6 bg-blue-500 mr-3 rounded-full"></span>
            What is Tree Isomorphism?
          </h1>
          <div className="prose dark:prose-invert max-w-none">
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              {paragraphs[0]}
            </p>
          </div>
        </section>

        {/* How it works */}
        <section className="p-6 border-b border-gray-100 dark:border-gray-700">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-4 flex items-center">
            <span className="w-1 h-6 bg-blue-500 mr-3 rounded-full"></span>
            How Does It Work?
          </h1>
          <div className="prose dark:prose-invert max-w-none mb-4">
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              {paragraphs[1]}
            </p>
          </div>
          <div className="prose dark:prose-invert max-w-none mb-4">
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
              {paragraphs[2]}
            </p>
          </div>

          <div className="text-sm font-medium text-center text-gray-600 dark:text-gray-400 mb-2">
            Tree B is Tree A with children swapped at nodes 1 and 3, so they're isomorphic
          </div>
          <WalkthroughDiagram />

          <div className="mt-4 flex flex-wrap items-center justify-center gap-3 text-xs text-gray-500 dark:text-gray-400">
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded-full border-2 border-dashed border-violet-500 inline-block"></span>
              Children swapped
            </span>
          </div>
        </section>

        {/* Algorithm Steps */}
        <section className="p-6 border-b border-gray-100 dark:border-gray-700">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-4 flex items-center">
            <span className="w-1 h-6 bg-blue-500 mr-3 rounded-full"></span>
            Algorithm Steps
          </h1>
          <div className="prose dark:prose-invert max-w-none">
            <ol className="space-y-3 list-decimal pl-5 marker:text-gray-500 dark:marker:text-gray-400">
              {algorithm.map((item, index) => (
                <li key={index} className="text-gray-700 dark:text-gray-300 pl-2">
                  {item.points}
                  {item.subpoints && (
                    <ul className="mt-2 space-y-2 list-disc pl-5 marker:text-gray-400 dark:marker:text-gray-500">
                      {item.subpoints.map((subitem, subindex) => (
                        <li key={subindex} className="text-gray-600 dark:text-gray-400">
                          {subitem}
                        </li>
                      ))}
                    </ul>
                  )}
                </li>
              ))}
            </ol>
          </div>
        </section>

        {/* Time Complexity */}
        <section className="p-6 border-b border-gray-100 dark:border-gray-700">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-4 flex items-center">
            <span className="w-1 h-6 bg-blue-500 mr-3 rounded-full"></span>
            Time Complexity
          </h1>
          <div className="prose dark:prose-invert max-w-none">
            <ul className="space-y-3 list-disc pl-5 marker:text-gray-500 dark:marker:text-gray-400">
              {complexity.map((item, index) => (
                <li key={index} className="text-gray-700 dark:text-gray-300 pl-2">
                  <span className="font-mono bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded text-sm">
                    {item.points.split(":")[0]}:
                  </span>
                  <span className="ml-2">{item.points.split(":")[1]}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="mt-8">
            <ComplexityGraph
              bestCase={(n) => n}
              averageCase={(n) => n}
              worstCase={(n) => n * n}
              maxN={20}
            />
          </div>

          <InContentAd />
        </section>

        {/* Additional Info */}
        <section className="p-6">
          <div className="prose dark:prose-invert max-w-none">
            <div className="px-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                {paragraphs[3]}
              </p>
            </div>
          </div>
        </section>
      </article>
      <NewsletterEmbed mobile theme={theme} />
      <DailyDSAEmbed mobile theme={theme} />
    </main>
  );
};

export default Content;
